export const SET_ACTION_PLAN = "SET_ACTION_PLAN";
export const SET_ACTION_PLAN_ID = "SET_ACTION_PLAN_ID"; 
export const SET_ORDER_BY = "SET_ORDER_BY";
export const SET_FORMED_BY = "SET_FORMED_BY";
export const SET_NOTE = "SET_NOTE";
export const SET_DATE = "SET_DATE";
export const SET_ACTION_PLAN_NAME = "SET_ACTION_PLAN_NAME";
export const SET_ACTION_PLAN_UPDATE = "SET_ACTION_PLAN_UPDATE";
export const GET_ACTION_PLAN_BY_IDNAME = "GET_ACTION_PLAN_BY_IDNAME";
export const GET_ActionPlan_ERROR = "GET_ActionPlan_ERROR";

export const SET_CHECKLIST_ACTION = "SET_CHECKLIST_ACTION";
export const SET_POSTURE_ACTION = "SET_POSTURE_ACTION";
export const SET_REPETITIWORK_ACTION = "SET_REPETITIWORK_ACTION";
export const SET_LIFTING_WORK_ACTION = "SET_LIFTING_WORK_ACTION";
export const SET_PUSHING_AND_PULLING_WORK_ACTION = "SET_PUSHING_AND_PULLING_WORK_ACTION";
export const SET_INFLUENCING_FACTORS_ACTIONS = "SET_INFLUENCING_FACTORS_ACTIONS";
export const SET_PHYSICALLY_STRENUOUS_WORK_ACTIONS ="SET_PHYSICALLY_STRENUOUS_WORK_ACTIONS";
export const SET_PHYSICAL_DISCOMFORT_ACTIONS = "SET_PHYSICAL_DISCOMFORT_ACTIONS";
export const SET_UPDATE_STATUS = "SET_UPDATE_STATUS";
export const SET_USER ="SET_USER";
export const SET_CHECKLIST_SAVE_ERROR_AP = "SET_CHECKLIST_SAVE_ERROR_AP";
export const SET_CHECKLIST_BY_ID_ERROR_AP = "SET_CHECKLIST_BY_ID_ERROR_AP";

