export const SET_INFLUENCING_FACTORS_ACTIONS = "SET_INFLUENCING_FACTORS_ACTIONS";
export const SET_INFLUENCING_FACTORS_ACTIONS_ID = "SET_INFLUENCING_FACTORS_ACTIONS_ID";

export const SET_PLANNED_ACTIONS51A = "SET_PLANNED_ACTIONS51A";
export const SET_BYWHOM51A = "SET_BYWHOM51A";
export const SET_DATE51A = "SET_DATE51A";
export const SET_READY_DATE51A = "SET_READY_DATE51A";
export const SET_FOLLOW_UPDATE51A = "SET_FOLLOW_UPDATE51A";

export const SET_PLANNED_ACTIONS51B = "SET_PLANNED_ACTIONS51B";
export const SET_BYWHOM51B = "SET_BYWHOM51B";
export const SET_DATE51B = "SET_DATE51B";
export const SET_READY_DATE51B = "SET_READY_DATE51B";
export const SET_FOLLOW_UPDATE51B = "SET_FOLLOW_UPDATE51B";

export const SET_PLANNED_ACTIONS51C = "SET_PLANNED_ACTIONS51C";
export const SET_BYWHOM51C = "SET_BYWHOM51C";
export const SET_DATE51C = "SET_DATE51C";
export const SET_READY_DATE51C = "SET_READY_DATE51C";
export const SET_FOLLOW_UPDATE51C = "SET_FOLLOW_UPDATE51C";

export const SET_PLANNED_ACTIONS51D = "SET_PLANNED_ACTIONS51D";
export const SET_BYWHOM51D = "SET_BYWHOM51D";
export const SET_DATE51D = "SET_DATE51D";
export const SET_READY_DATE51D = "SET_READY_DATE51D";
export const SET_FOLLOW_UPDATE51D = "SET_FOLLOW_UPDATE51D";

export const SET_PLANNED_ACTIONS51E = "SET_PLANNED_ACTIONS51E";
export const SET_BYWHOM51E = "SET_BYWHOM51E";
export const SET_DATE51E = "SET_DATE51E";
export const SET_READY_DATE51E = "SET_READY_DATE51E";
export const SET_FOLLOW_UPDATE51E = "SET_FOLLOW_UPDATE51E";

export const SET_PLANNED_ACTIONS51F = "SET_PLANNED_ACTIONS51F";
export const SET_BYWHOM51F = "SET_BYWHOM51F";
export const SET_DATE51F = "SET_DATE51F";
export const SET_READY_DATE51F = "SET_READY_DATE51F";
export const SET_FOLLOW_UPDATE51F = "SET_FOLLOW_UPDATE51F";

export const SET_PLANNED_ACTIONS52A = "SET_PLANNED_ACTIONS52A";
export const SET_BYWHOM52A = "SET_BYWHOM52A";
export const SET_DATE52A = "SET_DATE52A";
export const SET_READY_DATE52A = "SET_READY_DATE52A";
export const SET_FOLLOW_UPDATE52A = "SET_FOLLOW_UPDATE52A";

export const SET_PLANNED_ACTIONS52B = "SET_PLANNED_ACTIONS52B";
export const SET_BYWHOM52B = "SET_BYWHOM52B";
export const SET_DATE52B = "SET_DATE52B";
export const SET_READY_DATE52B = "SET_READY_DATE52B";
export const SET_FOLLOW_UPDATE52B = "SET_FOLLOW_UPDATE52B";

export const SET_PLANNED_ACTIONS52C = "SET_PLANNED_ACTIONS52C";
export const SET_BYWHOM52C = "SET_BYWHOM52C";
export const SET_DATE52C = "SET_DATE52C";
export const SET_READY_DATE52C = "SET_READY_DATE52C";
export const SET_FOLLOW_UPDATE52C = "SET_FOLLOW_UPDATE52C";

export const SET_PLANNED_ACTIONS52D = "SET_PLANNED_ACTIONS52D";
export const SET_BYWHOM52D = "SET_BYWHOM52D";
export const SET_DATE52D = "SET_DATE52D";
export const SET_READY_DATE52D = "SET_READY_DATE52D";
export const SET_FOLLOW_UPDATE52D = "SET_FOLLOW_UPDATE52D";

export const SET_PLANNED_ACTIONS52E = "SET_PLANNED_ACTIONS52E";
export const SET_BYWHOM52E = "SET_BYWHOM52E";
export const SET_DATE52E = "SET_DATE52E";
export const SET_READY_DATE52E = "SET_READY_DATE52E";
export const SET_FOLLOW_UPDATE52E = "SET_FOLLOW_UPDATE52E";

export const SET_PLANNED_ACTIONS52F = "SET_PLANNED_ACTIONS52F";
export const SET_BYWHOM52F = "SET_BYWHOM52F";
export const SET_DATE52F = "SET_DATE52F";
export const SET_READY_DATE52F = "SET_READY_DATE52F";
export const SET_FOLLOW_UPDATE52F = "SET_FOLLOW_UPDATE52F";

export const SET_PLANNED_ACTIONS52G = "SET_PLANNED_ACTIONS52G";
export const SET_BYWHOM52G = "SET_BYWHOM52G";
export const SET_DATE52G = "SET_DATE52G";
export const SET_READY_DATE52G = "SET_READY_DATE52G";
export const SET_FOLLOW_UPDATE52G = "SET_FOLLOW_UPDATE52G";

export const SET_PLANNED_ACTIONS52H = "SET_PLANNED_ACTIONS52H";
export const SET_BYWHOM52H = "SET_BYWHOM52H";
export const SET_DATE52H = "SET_DATE52H";
export const SET_READY_DATE52H = "SET_READY_DATE52H";
export const SET_FOLLOW_UPDATE52H = "SET_FOLLOW_UPDATE52H";

export const SET_PLANNED_ACTIONS53A = "SET_PLANNED_ACTIONS53A";
export const SET_BYWHOM53A = "SET_BYWHOM53A";
export const SET_DATE53A = "SET_DATE53A";
export const SET_READY_DATE53A = "SET_READY_DATE53A";
export const SET_FOLLOW_UPDATE53A = "SET_FOLLOW_UPDATE53A";

export const SET_PLANNED_ACTIONS53B = "SET_PLANNED_ACTIONS53B";
export const SET_BYWHOM53B = "SET_BYWHOM53B";
export const SET_DATE53B = "SET_DATE53B";
export const SET_READY_DATE53B = "SET_READY_DATE53B";
export const SET_FOLLOW_UPDATE53B = "SET_FOLLOW_UPDATE53B";

export const SET_PLANNED_ACTIONS53C = "SET_PLANNED_ACTIONS53C";
export const SET_BYWHOM53C = "SET_BYWHOM53C";
export const SET_DATE53C = "SET_DATE53C";
export const SET_READY_DATE53C = "SET_READY_DATE53C";
export const SET_FOLLOW_UPDATE53C = "SET_FOLLOW_UPDATE53C";

export const SET_PLANNED_ACTIONS53D = "SET_PLANNED_ACTIONS53D";
export const SET_BYWHOM53D = "SET_BYWHOM53D";
export const SET_DATE53D = "SET_DATE53D";
export const SET_READY_DATE53D = "SET_READY_DATE53D";
export const SET_FOLLOW_UPDATE53D = "SET_FOLLOW_UPDATE53D";
