export const SET_LIFTING_WORK_ACTIONS = "SET_LIFTING_WORK_ACTIONS";
export const SET_LIFTING_WORK_ACTIONS_ID = "SET_LIFTING_WORK_ACTIONS_ID";

export const SET_PLANNED_ACTIONS31 = "SET_PLANNED_ACTIONS31";
export const SET_BYWHOM31 = "SET_BYWHOM31";
export const SET_DATE31 = "SET_DATE31";
export const SET_READY_DATE31 = "SET_READY_DATE31";
export const SET_FOLLOW_UPDATE31 = "SET_FOLLOW_UPDATE31";

export const SET_PLANNED_ACTIONS32 = "SET_PLANNED_ACTIONS32";
export const SET_BYWHOM32 = "SET_BYWHOM32";
export const SET_DATE32 = "SET_DATE32";
export const SET_READY_DATE32 = "SET_READY_DATE32";
export const SET_FOLLOW_UPDATE32 = "SET_FOLLOW_UPDATE32";


