export const SET_PHYSICAL_DISCOMFORT_ACTIONS = "SET_PHYSICAL_DISCOMFORT_ACTIONS";
export const SET_PHYSICAL_DISCOMFORT_ACTIONS_ID = "SET_PHYSICAL_DISCOMFORT_ACTIONS_ID";

export const SET_PLANNED_ACTIONS71 = "SET_PLANNED_ACTIONS71";
export const SET_BYWHOM71 = "SET_BYWHOM71";
export const SET_DATE71 = "SET_DATE71";
export const SET_READY_DATE71 = "SET_READY_DATE71";
export const SET_FOLLOW_UPDATE71 = "SET_FOLLOW_UPDATE71";


