export const SET_PHYSICALLY_STRENUOUS_WORK_ACTIONS = "SET_PHYSICALLY_STRENUOUS_WORK_ACTIONS";
export const SET_PHYSICALLY_STRENUOUS_WORK_ACTIONS_ID = "SET_PHYSICALLY_STRENUOUS_WORK_ACTIONS_ID";

export const SET_PLANNED_ACTIONS61 = "SET_PLANNED_ACTIONS61";
export const SET_BYWHOM61 = "SET_BYWHOM61";
export const SET_DATE61 = "SET_DATE61";
export const SET_READY_DATE61 = "SET_READY_DATE61";
export const SET_FOLLOW_UPDATE61 = "SET_FOLLOW_UPDATE61";


