export const SET_POSTURE_ACTIONS = "SET_POSTURE_ACTIONS";
export const SET_POSTURE_ACTIONS_ID = "SET_POSTURE_ACTIONS_ID";

export const SET_PLANNED_ACTIONS11 = "SET_PLANNED_ACTIONS11";
export const SET_BYWHOM11 = "SET_BYWHOM11";
export const SET_DATE11 = "SET_DATE11";
export const SET_READY_DATE11 = "SET_READY_DATE11";
export const SET_FOLLOW_UPDATE11 = "SET_FOLLOW_UPDATE11";

export const SET_PLANNED_ACTIONS12 = "SET_PLANNED_ACTIONS12";
export const SET_BYWHOM12 = "SET_BYWHOM12";
export const SET_DATE12 = "SET_DATE12";
export const SET_READY_DATE12 = "SET_READY_DATE12";
export const SET_FOLLOW_UPDATE12 = "SET_FOLLOW_UPDATE12";

export const SET_PLANNED_ACTIONS13 = "SET_PLANNED_ACTIONS13";
export const SET_BYWHOM13 = "SET_BYWHOM13";
export const SET_DATE13 = "SET_DATE13";
export const SET_READY_DATE13 = "SET_READY_DATE13";
export const SET_FOLLOW_UPDATE13 = "SET_FOLLOW_UPDATE13";

export const SET_PLANNED_ACTIONS14 = "SET_PLANNED_ACTIONS14";
export const SET_BYWHOM14 = "SET_BYWHOM14";
export const SET_DATE14 = "SET_DATE14";
export const SET_READY_DATE14 = "SET_READY_DATE14";
export const SET_FOLLOW_UPDATE14 = "SET_FOLLOW_UPDATE14";

export const SET_PLANNED_ACTIONS15 = "SET_PLANNED_ACTIONS15";
export const SET_BYWHOM15 = "SET_BYWHOM15";
export const SET_DATE15 = "SET_DATE15";
export const SET_READY_DATE15 = "SET_READY_DATE15";
export const SET_FOLLOW_UPDATE15 = "SET_FOLLOW_UPDATE15";

export const SET_PLANNED_ACTIONS16 = "SET_PLANNED_ACTIONS16";
export const SET_BYWHOM16 = "SET_BYWHOM16";
export const SET_DATE16 = "SET_DATE16";
export const SET_READY_DATE16 = "SET_READY_DATE16";
export const SET_FOLLOW_UPDATE16 = "SET_FOLLOW_UPDATE16";

export const SET_PLANNED_ACTIONS17 = "SET_PLANNED_ACTIONS17";
export const SET_BYWHOM17 = "SET_BYWHOM17";
export const SET_DATE17 = "SET_DATE17";
export const SET_READY_DATE17 = "SET_READY_DATE17";
export const SET_FOLLOW_UPDATE17 = "SET_FOLLOW_UPDATE17";


export const SET_PLANNED_ACTIONS18 = "SET_PLANNED_ACTIONS18";
export const SET_BYWHOM18 = "SET_BYWHOM18";
export const SET_DATE18 = "SET_DATE18";
export const SET_READY_DATE18 = "SET_READY_DATE18";
export const SET_FOLLOW_UPDATE18 = "SET_FOLLOW_UPDATE18";

