export const SET_PUSHING_AND_PULLING_WORK_ACTIONS = "SET_PUSHING_AND_PULLING_WORK_ACTIONS";
export const SET_PUSHING_AND_PULLING_WORK_ACTIONS_ID = "SET_PUSHING_AND_PULLING_WORK_ACTIONS_ID";

export const SET_PLANNED_ACTIONS41 = "SET_PLANNED_ACTIONS41";
export const SET_BYWHOM41 = "SET_BYWHOM41";
export const SET_DATE41 = "SET_DATE41";
export const SET_READY_DATE41 = "SET_READY_DATE41";
export const SET_FOLLOW_UPDATE41 = "SET_FOLLOW_UPDATE41";

export const SET_PLANNED_ACTIONS42 = "SET_PLANNED_ACTIONS42";
export const SET_BYWHOM42 = "SET_BYWHOM42";
export const SET_DATE42 = "SET_DATE42";
export const SET_READY_DATE42 = "SET_READY_DATE42";
export const SET_FOLLOW_UPDATE42 = "SET_FOLLOW_UPDATE42";


