export const SET_REPETITIVE_WORK_ACTIONS = "SET_REPETITIVE_WORK_ACTIONS";
export const SET_REPETITIVE_WORK_ACTIONS_ID = "SET_REPETITIVE_WORK_ACTIONS_ID";

export const SET_PLANNED_ACTIONS21 = "SET_PLANNED_ACTIONS21";
export const SET_BYWHOM21 = "SET_BYWHOM21";
export const SET_DATE21 = "SET_DATE21";
export const SET_READY_DATE21 = "SET_READY_DATE21";
export const SET_FOLLOW_UPDATE21 = "SET_FOLLOW_UPDATE21";

export const SET_PLANNED_ACTIONS22 = "SET_PLANNED_ACTIONS22";
export const SET_BYWHOM22 = "SET_BYWHOM22";
export const SET_DATE22 = "SET_DATE22";
export const SET_READY_DATE22 = "SET_READY_DATE22";
export const SET_FOLLOW_UPDATE22 = "SET_FOLLOW_UPDATE22";

export const SET_PLANNED_ACTIONS23 = "SET_PLANNED_ACTIONS23";
export const SET_BYWHOM23 = "SET_BYWHOM23";
export const SET_DATE23 = "SET_DATE23";
export const SET_READY_DATE23 = "SET_READY_DATE23";
export const SET_FOLLOW_UPDATE23 = "SET_FOLLOW_UPDATE23";

export const SET_PLANNED_ACTIONS24 = "SET_PLANNED_ACTIONS24";
export const SET_BYWHOM24 = "SET_BYWHOM24";
export const SET_DATE24 = "SET_DATE24";
export const SET_READY_DATE24 = "SET_READY_DATE24";
export const SET_FOLLOW_UPDATE24 = "SET_FOLLOW_UPDATE24";

export const SET_PLANNED_ACTIONS25 = "SET_PLANNED_ACTIONS25";
export const SET_BYWHOM25 = "SET_BYWHOM25";
export const SET_DATE25 = "SET_DATE25";
export const SET_READY_DATE25 = "SET_READY_DATE25";
export const SET_FOLLOW_UPDATE25 = "SET_FOLLOW_UPDATE25";


