export const SET_CHECKLISTNAME = "SET_CHECKLISTNAME";

export const SET_ID = "SET_ID";

export const SET_CHECKLIST = "SET_CHECKLIST";

export const SET_CHECKLIST_COMPLETION = "SET_CHECKLIST_COMPLETION";

export const SET_INPUTDATA = "SET_INPUTDATA";

export const SET_LIFTINGWORK = "SET_LIFTINGWORK";

export const SET_POSTURE = "SET_POSTURE";

export const SET_REPETITIVEWORK = "SET_REPETITIVEWORK";

export const SET_INFLUENCINGFACTORS = "SET_INFLUENCINGFACTORS";

export const SET_PHYSICALLYSTRENUOUSWORK = "SET_PHYSICALLYSTRENUOUSWORK";

export const SET_PHYSICALDISCOMFORT = "SET_PHYSICALDISCOMFORT";

export const SET_PUSHINGANDPULLING = "SET_PUSHINGANDPULLING";

export const SET_OTHERCOMMENT = "SET_OTHERCOMMENT";

export const GET_CHECKLIST_BY_ID = "GET_CHECKLIST_BY_ID";

export const SET_CHECKLIST_BY_ID_ERROR = "SET_CHECKLIST_BY_ID_ERROR";

export const SET_CHECKLIST_SAVE_ERROR = "SET_CHECKLIST_SAVE_ERROR";

export const SET_UPDATE_CHECKLIST = "SET_UPDATE_CHECKLIST";

export const SET_COMPLETED = "SET_COMPLETED";

export const SET_USER = "SET_USER";
