export const SET_INPUTDATA = "SET_INPUTDATA";

export const SET_ID = "SET_ID";

export const SET_DATE = "SET_DATE";

export const SET_WORK = "SET_WORK";

export const SET_ASSESMENTOF = "SET_ASSESMENTOF";

export const SET_WORKSTATION = "SET_WORKSTATION";

export const SET_DEPARTMENT = "SET_DEPARTMENT";

export const SET_SITE = "SET_SITE";

export const SET_COUNTRY = "SET_COUNTRY";

export const SET_ASSESMENTORDEREDBY = "SET_ASSESMENTORDEREDBY";

export const SET_POSITIONONE = "SET_POSITIONONE";

export const SET_ASSESMENTCOMPLETEDBY = "SET_ASSESMENTCOMPLETEDBY";

export const SET_POSITIONTWO = "SET_POSITIONTWO";

export const SET_COMPANYREPRESENTATIVE = "SET_COMPANYREPRESENTATIVE";

export const SET_POSITIONTHREE = "SET_POSITIONTHREE";

export const SET_SAFETYPERSONNEL = "SET_SAFETYPERSONNEL";

export const SET_POSITIONFOUR = "SET_POSITIONFOUR";

export const SET_OTHER = "SET_OTHER";

export const SET_POSITIONFIVE = "SET_POSITIONFIVE";

export const SET_OTHERINFORMATION = "SET_OTHERINFORMATION";
